# Generated by Django 4.0.2 on 2022-07-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='author_name',
            new_name='authors_name',
        ),
    ]
