# Generated by Django 4.0.2 on 2022-04-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='client_name',
            new_name='authors_name',
        ),
    ]
