# Generated by Django 4.0.2 on 2022-07-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_rename_client_name_subscriber_authors_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
